### ISSUE TITLE
Couldn't find any output plugin named 'example'

### ISSUE THREAD

**Issue by swsachith** [logstash-plugins/logstash-output-example#3]
Hi,

I followed the example on how to write an output plugin for logstash[1].

When I install the gem it shows up at bin/plugin list. But when I try to call it in a conf file ex:
output{
example{}
}

it gives me the error: "The error reported is: 
  Couldn't find any output plugin named 'example'. Are you sure this is correct? Trying to load the example output plugin resulted in this error: no such file to load -- logstash/outputs/example
"

Any suggestions ?

[1] https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html

**Comment by purbon** [comment]
This is not an actual released gem, or plugin so you can not really install it without building it. I'm sure you had some issue while building the plugin, like might be not doing `git commit` with your changes? For support/help questions I encourage you to ask at https://discuss.elastic.co/c/logstash, there you will find lots of help, and might be already the answer to your issue :+1: 

/cheers
